[general]
use_middle_proxy = false

[general.links]
show ="*"

[censorship]
tls_domain = "max.ru"
tls_domains = ["max.ru", "hd.kinopoisk.ru", "my.mail.ru", "avito.ru", "microsoft.com", "drive.google.com"]
tls_emulation = true

[access.users]
hello = "be3007e927acd147dde12bee8b1a7c93"

[server]
port = 443
metrics_port = 9090
metrics_whitelist = ["127.0.0.1", "::1"]

